"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Wallet_App.py']
DATA_FILES = ['bitcoin_logo.png', 'wallet_file.json']
OPTIONS = {'argv_emulation': True,
           'iconfile':'icon_mac.icns', 'packages':['requests','matplotlib']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
